# Generated by Django 3.2.7 on 2021-11-29 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('yearPlan', '0002_alter_yearplan_year'),
        ('workOrder', '0002_rename_workoders_directive_workorders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('dateTimeCreate', models.DateTimeField(auto_now_add=True)),
                ('workOrder', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='workOrder.workorder')),
                ('yearPlan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='yearPlan.yearplan')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sContCant', models.FloatField(default=0)),
                ('sContTotal', models.FloatField(default=0)),
                ('sSubCant', models.FloatField(default=0)),
                ('sSubPrice', models.FloatField(default=0)),
                ('sTeCant', models.FloatField(default=0)),
                ('sTeTotal', models.FloatField(default=0)),
                ('um', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('diff', models.FloatField(default=0)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventoryItems', to='inventory.inventory')),
            ],
        ),
    ]
