# Generated by Django 3.2.7 on 2021-10-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YearPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=0)),
                ('cantidadAudit', models.PositiveSmallIntegerField(default=0)),
                ('diasAudit', models.PositiveSmallIntegerField(default=0)),
                ('diasFeriad', models.PositiveSmallIntegerField(default=0)),
                ('diasVacaciones', models.PositiveSmallIntegerField(default=0)),
                ('diasCapacitacion', models.PositiveSmallIntegerField(default=0)),
                ('diasReservas', models.PositiveSmallIntegerField(default=0)),
                ('controlInterno', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
