# Generated by Django 3.2.7 on 2021-11-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearPlan', '0002_alter_yearplan_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearplan',
            name='author',
            field=models.CharField(default='', max_length=255),
        ),
    ]
