const Create={
    REQUEST:'INVENTORY_CREATE_REQUEST',
    SUCCESS:'INVENTORY_CREATE_SUCCESS',
    ERROR:'INVENTORY_CREATE_ERROR',
    RESET:'INVENTORY_CREATE_RESET',
}
const Update={
    REQUEST:'INVENTORY_UPDATE_REQUEST',
    SUCCESS:'INVENTORY_UPDATE_SUCCESS',
    ERROR:'INVENTORY_UPDATE_ERROR',
    RESET:'INVENTORY_UPDATE_RESET',
}
const Delete={
    REQUEST:'INVENTORY_DELETE_REQUEST',
    SUCCESS:'INVENTORY_DELETE_SUCCESS',
    ERROR:'INVENTORY_DELETE_ERROR',
    RESET:'INVENTORY_DELETE_RESET',
}
const Show={
    REQUEST:'INVENTORY_SHOW_REQUEST',
    SUCCESS:'INVENTORY_SHOW_SUCCESS',
    ERROR:'INVENTORY_SHOW_ERROR',
    RESET:'INVENTORY_SHOW_RESET',
}
const List={
    REQUEST:'INVENTORY_LIST_REQUEST',
    SUCCESS:'INVENTORY_LIST_SUCCESS',
    ERROR:'INVENTORY_LIST_ERROR',
    RESET:'INVENTORY_LIST_RESET',
}

export const inventoryActionTypes = {
    CREATE: Create,
    UPDATE: Update,
    DELETE: Delete,
    SHOW: Show,
    LIST: List,
}
