# Generated by Django 3.2.7 on 2021-10-30 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('yearPlan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('noWO', models.PositiveSmallIntegerField(default=0)),
                ('criteria', models.CharField(max_length=256)),
                ('system', models.CharField(max_length=256)),
                ('leader', models.CharField(max_length=256)),
                ('auditor1', models.CharField(max_length=256)),
                ('auditor2', models.CharField(max_length=256)),
                ('entity', models.CharField(max_length=256)),
                ('subordinated', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('province', models.CharField(max_length=256)),
                ('municipality', models.CharField(max_length=256)),
                ('NAE', models.CharField(max_length=256)),
                ('financingForm', models.CharField(max_length=256)),
                ('FORG', models.CharField(max_length=256)),
                ('cubanStateEntrpSys', models.CharField(max_length=256)),
                ('isPerfecting', models.BooleanField(default=False)),
                ('merchantSociety', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('yearPlan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workOrders', to='yearPlan.yearplan')),
            ],
        ),
        migrations.CreateModel(
            name='Directive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=128)),
                ('workOders', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='directives', to='workOrder.workorder')),
            ],
        ),
    ]
