# Generated by Django 3.2.7 on 2021-11-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0002_rename_workoders_directive_workorders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='financingForm',
        ),
        migrations.AddField(
            model_name='workorder',
            name='actionType',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='workorder',
            name='cantAuditores',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workorder',
            name='codNIT',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='workorder',
            name='codREEUP',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='workorder',
            name='diasHabiles',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='workorder',
            name='endDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='startDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='unidadPress',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='FORG',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='NAE',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='address',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='auditor1',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='auditor2',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='author',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='criteria',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='cubanStateEntrpSys',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='entity',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='leader',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='municipality',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='province',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='subordinated',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='system',
            field=models.CharField(default='', max_length=256),
        ),
    ]
