# Generated by Django 3.2.7 on 2021-11-29 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0003_auto_20211130_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='datetime',
            new_name='dateTimeCreated',
        ),
    ]
