# Generated by Django 3.2.7 on 2021-11-30 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0005_remove_workorder_forg'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='FORG',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='auditType',
            field=models.CharField(default='', max_length=256),
        ),
    ]
