const Create={
    REQUEST:'FINAL_REPORT_CREATE_REQUEST',
    SUCCESS:'FINAL_REPORT_CREATE_SUCCESS',
    ERROR:'FINAL_REPORT_CREATE_ERROR',
    RESET:'FINAL_REPORT_CREATE_RESET',
}
const Update={
    REQUEST:'FINAL_REPORT_UPDATE_REQUEST',
    SUCCESS:'FINAL_REPORT_UPDATE_SUCCESS',
    ERROR:'FINAL_REPORT_UPDATE_ERROR',
    RESET:'FINAL_REPORT_UPDATE_RESET',
}
const Delete={
    REQUEST:'FINAL_REPORT_DELETE_REQUEST',
    SUCCESS:'FINAL_REPORT_DELETE_SUCCESS',
    ERROR:'FINAL_REPORT_DELETE_ERROR',
    RESET:'FINAL_REPORT_DELETE_RESET',
}
const Show={
    REQUEST:'FINAL_REPORT_SHOW_REQUEST',
    SUCCESS:'FINAL_REPORT_SHOW_SUCCESS',
    ERROR:'FINAL_REPORT_SHOW_ERROR',
    RESET:'FINAL_REPORT_SHOW_RESET',
}
const List={
    REQUEST:'FINAL_REPORT_LIST_REQUEST',
    SUCCESS:'FINAL_REPORT_LIST_SUCCESS',
    ERROR:'FINAL_REPORT_LIST_ERROR',
    RESET:'FINAL_REPORT_LIST_RESET',
}

export const FinalReportActionTypes = {
    CREATE: Create,
    UPDATE: Update,
    DELETE: Delete,
    SHOW: Show,
    LIST: List,
}
