const Create={
    REQUEST:'WORK_SHEET_CREATE_REQUEST',
    SUCCESS:'WORK_SHEET_CREATE_SUCCESS',
    ERROR:'WORK_SHEET_CREATE_ERROR',
    RESET:'WORK_SHEET_CREATE_RESET',
}
const Update={
    REQUEST:'WORK_SHEET_UPDATE_REQUEST',
    SUCCESS:'WORK_SHEET_UPDATE_SUCCESS',
    ERROR:'WORK_SHEET_UPDATE_ERROR',
    RESET:'WORK_SHEET_UPDATE_RESET',
}
const Delete={
    REQUEST:'WORK_SHEET_DELETE_REQUEST',
    SUCCESS:'WORK_SHEET_DELETE_SUCCESS',
    ERROR:'WORK_SHEET_DELETE_ERROR',
    RESET:'WORK_SHEET_DELETE_RESET',
}
const Show={
    REQUEST:'WORK_SHEET_SHOW_REQUEST',
    SUCCESS:'WORK_SHEET_SHOW_SUCCESS',
    ERROR:'WORK_SHEET_SHOW_ERROR',
    RESET:'WORK_SHEET_SHOW_RESET',
}
const List={
    REQUEST:'WORK_SHEET_LIST_REQUEST',
    SUCCESS:'WORK_SHEET_LIST_SUCCESS',
    ERROR:'WORK_SHEET_LIST_ERROR',
    RESET:'WORK_SHEET_LIST_RESET',
}

export const WorkSheetActionTypes = {
    CREATE: Create,
    UPDATE: Update,
    DELETE: Delete,
    SHOW: Show,
    LIST: List,
}
