const Create = {
  REQUEST: "wORK_ORDER_CREATE_REQUEST",
  SUCCESS: "wORK_ORDER_CREATE_SUCCESS",
  ERROR: "wORK_ORDER_CREATE_ERROR",
  RESET: "wORK_ORDER_CREATE_RESET",
};
const Update = {
  REQUEST: "wORK_ORDER_UPDATE_REQUEST",
  SUCCESS: "wORK_ORDER_UPDATE_SUCCESS",
  ERROR: "wORK_ORDER_UPDATE_ERROR",
  RESET: "wORK_ORDER_UPDATE_RESET",
};
const Delete = {
  REQUEST: "wORK_ORDER_DELETE_REQUEST",
  SUCCESS: "wORK_ORDER_DELETE_SUCCESS",
  ERROR: "wORK_ORDER_DELETE_ERROR",
  RESET: "wORK_ORDER_DELETE_RESET",
};
const Show = {
  REQUEST: "wORK_ORDER_SHOW_REQUEST",
  SUCCESS: "wORK_ORDER_SHOW_SUCCESS",
  ERROR: "wORK_ORDER_SHOW_ERROR",
  RESET: "wORK_ORDER_SHOW_RESET",
};
const List = {
  REQUEST: "wORK_ORDER_LIST_REQUEST",
  SUCCESS: "wORK_ORDER_LIST_SUCCESS",
  ERROR: "wORK_ORDER_LIST_ERROR",
  RESET: "wORK_ORDER_LIST_RESET",
};

const DETAILS = {
  REQUEST: "wORK_ORDER_DETAILS_REQUEST",
  SUCCESS: "wORK_ORDER_DETAILS_SUCCESS",
  ERROR: "wORK_ORDER_DETAILS_ERROR",
  RESET: "wORK_ORDER_DETAILS_RESET",
};

export const WorkOrderActionTypes = {
  CREATE: Create,
  UPDATE: Update,
  DELETE: Delete,
  SHOW: Show,
  LIST: List,
  DETAILS: DETAILS,
};
