const Create={
    REQUEST:'DEFICIENCY_SUMMARY_CREATE_REQUEST',
    SUCCESS:'DEFICIENCY_SUMMARY_CREATE_SUCCESS',
    ERROR:'DEFICIENCY_SUMMARY_CREATE_ERROR',
    RESET:'DEFICIENCY_SUMMARY_CREATE_RESET',
}
const Update={
    REQUEST:'DEFICIENCY_SUMMARY_UPDATE_REQUEST',
    SUCCESS:'DEFICIENCY_SUMMARY_UPDATE_SUCCESS',
    ERROR:'DEFICIENCY_SUMMARY_UPDATE_ERROR',
    RESET:'DEFICIENCY_SUMMARY_UPDATE_RESET',
}
const Delete={
    REQUEST:'DEFICIENCY_SUMMARY_DELETE_REQUEST',
    SUCCESS:'DEFICIENCY_SUMMARY_DELETE_SUCCESS',
    ERROR:'DEFICIENCY_SUMMARY_DELETE_ERROR',
    RESET:'DEFICIENCY_SUMMARY_DELETE_RESET',
}
const Show={
    REQUEST:'DEFICIENCY_SUMMARY_SHOW_REQUEST',
    SUCCESS:'DEFICIENCY_SUMMARY_SHOW_SUCCESS',
    ERROR:'DEFICIENCY_SUMMARY_SHOW_ERROR',
    RESET:'DEFICIENCY_SUMMARY_SHOW_RESET',
}
const List={
    REQUEST:'DEFICIENCY_SUMMARY_LIST_REQUEST',
    SUCCESS:'DEFICIENCY_SUMMARY_LIST_SUCCESS',
    ERROR:'DEFICIENCY_SUMMARY_LIST_ERROR',
    RESET:'DEFICIENCY_SUMMARY_LIST_RESET',
}


export const DeficiencySummaryActionTypes = {
    CREATE: Create,
    UPDATE: Update,
    DELETE: Delete,
    SHOW: Show,
    LIST: List,
}