const Create={
    REQUEST:'YEAR_PLAN_CREATE_REQUEST',
    SUCCESS:'YEAR_PLAN_CREATE_SUCCESS',
    ERROR:'YEAR_PLAN_CREATE_ERROR',
    RESET:'YEAR_PLAN_CREATE_RESET',
}
const Update={
    REQUEST:'YEAR_PLAN_UPDATE_REQUEST',
    SUCCESS:'YEAR_PLAN_UPDATE_SUCCESS',
    ERROR:'YEAR_PLAN_UPDATE_ERROR',
    RESET:'YEAR_PLAN_UPDATE_RESET',
}
const Delete={
    REQUEST:'YEAR_PLAN_DELETE_REQUEST',
    SUCCESS:'YEAR_PLAN_DELETE_SUCCESS',
    ERROR:'YEAR_PLAN_DELETE_ERROR',
    RESET:'YEAR_PLAN_DELETE_RESET',
}
const Details={
    REQUEST:'YEAR_PLAN_SHOW_REQUEST',
    SUCCESS:'YEAR_PLAN_SHOW_SUCCESS',
    ERROR:'YEAR_PLAN_SHOW_ERROR',
    RESET:'YEAR_PLAN_SHOW_RESET',
}
const List={
    REQUEST:'YEAR_PLAN_LIST_REQUEST',
    SUCCESS:'YEAR_PLAN_LIST_SUCCESS',
    ERROR:'YEAR_PLAN_LIST_ERROR',
    RESET:'YEAR_PLAN_LIST_RESET',
}

export const YearPlanActionTypes = {
    CREATE: Create,
    UPDATE: Update,
    DELETE: Delete,
    DETAILS: Details,
    LIST: List,
}
