const Create={
    REQUEST:'FILE_CREATE_REQUEST',
    SUCCESS:'FILE_CREATE_SUCCESS',
    ERROR:'FILE_CREATE_ERROR',
    RESET:'FILE_CREATE_RESET',
}
const Update={
    REQUEST:'FILE_UPDATE_REQUEST',
    SUCCESS:'FILE_UPDATE_SUCCESS',
    ERROR:'FILE_UPDATE_ERROR',
    RESET:'FILE_UPDATE_RESET',
}
const Delete={
    REQUEST:'FILE_DELETE_REQUEST',
    SUCCESS:'FILE_DELETE_SUCCESS',
    ERROR:'FILE_DELETE_ERROR',
    RESET:'FILE_DELETE_RESET',
}
const Show={
    REQUEST:'FILE_SHOW_REQUEST',
    SUCCESS:'FILE_SHOW_SUCCESS',
    ERROR:'FILE_SHOW_ERROR',
    RESET:'FILE_SHOW_RESET',
}
const List={
    REQUEST:'FILE_LIST_REQUEST',
    SUCCESS:'FILE_LIST_SUCCESS',
    ERROR:'FILE_LIST_ERROR',
    RESET:'FILE_LIST_RESET',
}

export const FileActionTypes = {
    CREATE: Create,
    UPDATE: Update,
    DELETE: Delete,
    SHOW: Show,
    LIST: List,
}