const LOGIN = {
  REQUEST: "LOGIN_REQUEST",
  SUCCESS: "LOGIN_SUCCESS",
  ERROR: "LOGIN_ERROR",
  RESET: "LOGIN_RESET",
};

export const UserActionTypes = {
  USER_LOGIN: LOGIN,
  USER_LOGOUT: "USER_LOGOUT",
  USER_CREATE: "USER_CREATE",
  USER_UPDATE: "USER_UPDATE",
  USER_DELETE: "USER_DELETE",
};
