const LOGIN = {
  REQUEST: "LOGIN_REQUEST",
  SUCCESS: "LOGIN_SUCCESS",
  ERROR: "LOGIN_ERROR",
  RESET: "LOGIN_RESET",
};

const USER_LOGIN_CHANGE_DATA = {
  REQUEST: "USER_LOGIN_CHANGE_DATA_REQUEST",
  SUCCESS: "USER_LOGIN_CHANGE_DATA_SUCCESS",
  ERROR: "USER_LOGIN_CHANGE_DATA_ERROR",
  RESET: "USER_LOGIN_CHANGE_DATA_RESET",
};
export const UserActionTypes = {
  USER_LOGIN: LOGIN,
  USER_LOGIN_CHANGE_DATA: USER_LOGIN_CHANGE_DATA,
  USER_CREATE: "USER_CREATE",
  USER_UPDATE: "USER_UPDATE",
  USER_DELETE: "USER_DELETE",
};
